CORTX-32769: Resolved pylint issues for src and scripts folder
Seagate/corio pull request #106
Opened 2022-08-25 09:12 UTC by SCP-Seagate

## Problem Statement

-   Problem statement

## Design

-   For Bug, Describe the fix here.
-   For new test addition post the link for design

## Coding

   Checklist for Author

-   [ ]  Coding conventions are followed and code is formatted (e.g. using pycharm in-built formatter)

## Testing

  Checklist for Author

-   [ ]  New/Affected tests are executed
-   [ ]  Attach test execution logs

## Review 

  Checklist for Author

-   [ ]  JIRA number/GitHub Issue added to PR
-   [ ]  PR is self reviewed
-   [ ]  Jira and state/status is updated and JIRA is updated with PR link
-   [ ]  Check if the description is clear and explained

## Documentation

  Checklist for Author

-   [ ]  Changes done to ReadMe

2022-08-25 10:52 UTC, DhobaleVishal requested changes

2022-08-25 10:52 UTC, DhobaleVishal commented on src/libs/tools/warp.py
> +    # pylint: disable=too-many-arguments,too-many-locals,too-many-instance-attributes
Instead of disabling pylint reported issues, can't we fix them if possible?

2022-08-25 10:54 UTC, DhobaleVishal commented
@SCP-Seagate Please fix `DCO Check` and `Codacy Static Code Analysis` for this PR.

2022-08-26 08:35 UTC, DhobaleVishal approved these changes

2022-08-26 08:42 UTC, DhobaleVishal commented on src/libs/tools/warp.py
> +    # pylint: disable=too-many-arguments,too-many-locals,too-many-instance-attributes
This is big change so, will be taken care later.

2022-08-26 10:12 UTC, VikasKumarC approved these changes
Approve to merge in dev

2022-08-26 10:12 UTC, merged