PR for Test Ids changes/correction in random size object yaml
Seagate/corio pull request #27
Opened 2022-03-24 14:28 UTC by azaharkhan

Signed-off-by: azahar.khan <azahar.khan@seagate.com>

# Problem Statement
PR for Test Ids changes/correction in random size object yaml

# Design
-  For Bug, Describe the fix here.
-  For new test addition post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is formatted (e.g. using pycharm in-built formatter)

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed
-  [ ] Attach test execution logs

# Review Checklist 
  Checklist for Author
-  [ ] JIRA number/GitHub Issue added to PR
-  [ ] PR is self reviewed
-  [ ] Jira and state/status is updated and JIRA is updated with PR link
-  [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe

2022-03-24 14:33 UTC, azaharkhan commented
@VikasKumarC  , @DhobaleVishal  , @ketanarlulkar  , @kulrk  , @priyankaborawake 
PR is raised for Test id changes/correction in Object operations for random sizes.
Please review.

2022-03-25 06:41 UTC, DhobaleVishal requested changes

2022-03-25 06:41 UTC, DhobaleVishal commented on config/s3/s3api/random_size_object.yaml
> +  TEST_ID: 35739
Test id should start with TEST-.

2022-03-25 11:59 UTC, VikasKumarC commented on config/s3/s3api/random_size_object.yaml
> +  TEST_ID: 35739
I am taking care this in my PR #26

2022-03-25 12:00 UTC, DhobaleVishal approved these changes

2022-03-25 12:00 UTC, VikasKumarC approved these changes

2022-03-25 12:00 UTC, merged