changed data directory path
Seagate/corio pull request #36
Opened 2022-04-08 06:55 UTC by kulrk

Signed-off-by: kulrk <rohan.1.kulkarni@seagate.com>

# Problem Statement
-  Problem statement

# Design
-  For Bug, Describe the fix here.
-  For new test addition post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is formatted (e.g. using pycharm in-built formatter)

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed
-  [ ] Attach test execution logs

# Review Checklist 
  Checklist for Author
-  [ ] JIRA number/GitHub Issue added to PR
-  [ ] PR is self reviewed
-  [ ] Jira and state/status is updated and JIRA is updated with PR link
-  [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe

2022-04-08 08:17 UTC, ketanarlulkar commented
You need to fix this in `scripts/s3/s3api/copy_object.py` too.

2022-04-08 10:48 UTC, ketanarlulkar approved these changes

2022-04-12 03:26 UTC, DhobaleVishal requested changes

2022-04-12 03:26 UTC, DhobaleVishal commented on src/commons/constants.py
> +DATA_DIR = 'data'
This should be TestData.

2022-04-12 05:37 UTC, kulrk commented on src/commons/constants.py
> +DATA_DIR = 'data'
Done

2022-04-18 08:08 UTC, DhobaleVishal approved these changes

2022-04-18 12:00 UTC, merged